app:
  name: user-service
  image: doceh/springboot-lib-app-aws
  port: 8080
  replicas: 2

env:
  dbUrl: jdbc:mysql://eks-db.cz82eooaw47s.ap-south-1.rds.amazonaws.com:3306/securelibrarymanagementsystem
  dbUser: root
  dbPass: "12345678"
  dbDriver: com.mysql.cj.jdbc.Driver

ingress:
  enabled: true
  host: ""

# -------------------------
# Namespace
# -------------------------
namespace: efk

# -------------------------
# StorageClass
# -------------------------
storageClass:
  name: manual
  provisioner: kubernetes.io/no-provisioner
  volumeBindingMode: WaitForFirstConsumer

# -------------------------
# PersistentVolumes
# -------------------------
persistentVolumes:
  - name: pv-elasticsearch-controlplane
    size: 5Gi
    accessMode: ReadWriteOnce
    path: /data/elasticsearch-controlplane
  - name: pv-elasticsearch-node01
    size: 5Gi
    accessMode: ReadWriteOnce
    path: /data/elasticsearch-node01
  - name: pv-elasticsearch-node02
    size: 5Gi
    accessMode: ReadWriteOnce
    path: /data/elasticsearch-node02

# -------------------------
# Elasticsearch
# -------------------------
elasticsearch:
  name: elasticsearch
  appLabel: elasticsearch
  replicas: 1
  image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
  pvSize: 5Gi
  security:
    enabled: "false"
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
  service:
    name: elasticsearch
    ports:
      http: 9200
      transport: 9300

# -------------------------
# Fluent Bit
# -------------------------
fluentbit:
  image: fluent/fluent-bit:2.1
  mainConf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Daemon       Off
        Parsers_File parsers.conf

    # Input - Kubernetes Container Logs
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Skip_Long_Lines   On
        Mem_Buf_Limit     5MB
        DB                /var/log/flb_kube.db

    # Kubernetes Metadata
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           On
        Merge_Log_Key       log
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    # Output to Elasticsearch
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-0.elasticsearch.efk.svc.cluster.local
        Port            9200
        Logstash_Format On
        Logstash_Prefix fluent-bit
        Time_Key        @timestamp
        Replace_Dots    On
        Retry_Limit     False

  parserConf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

# -------------------------
# Kibana
# -------------------------
kibana:
  replicas: 1
  image: docker.elastic.co/kibana/kibana:8.13.0
  port: 5601
  serviceType: ClusterIP   
  nodePort: null  

